Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Prefer and/or to &&/||
Style/AndOr:
  Enabled: false

# Prefer not to !
Style/Not:
  Enabled: false

# Always prefer double quotes ...
Style/StringLiterals:
  EnforcedStyle: double_quotes

# ... except when interpolating, e.g.,
# make_args = ["CC=#{ENV['CC']}"
# See https://github.com/bbatsov/rubocop/issues/1181
Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

# No need to document top-level class
Style/Documentation:
  Enabled: false

# Accept multiple spaces between method name and args, e.g.:
# url  "http://..."
# head "https://..."
#   vs
# url "http://..."
# head "https://..."
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/HashSyntax:
  Enabled: false

# Bug?
# https://github.com/AtomLinter/linter-rubocop/issues/2
Style/FileName:
  Enabled: false
